Account/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import  SignUp, AccountOptions, OrderHistory, ObservedBooks

app_name = 'Account'

urlpatterns = [
       path("", AccountOptions.as_view(), name="account_options" ),
       path("order-history/", OrderHistory.as_view(), name="order_history" ),
       path("signup/", SignUp.as_view(), name="sign_up" ),
       path("observed-books/", ObservedBooks.as_view(), name="observed_books" ),
       path("observed-books/<int:pk>/", ObservedBooks.as_view(), name="observed_books" ),
]

BookStore/urls.py

from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('Store.urls', namespace='Store')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Account.urls', namespace='Account')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name =  'Store'

urlpatterns = [
    path("", views.Index.as_view(), name='index'),
    path("books/<int:pk>/<slug:slug>/", views.BookDetail.as_view(), name='book_detail'),
    path("authors/", views.AuthorIndex.as_view(), name='author_index'),
    path("authors/<int:pk>/", views.AuthorDetail.as_view(), name='author_detail'),
    path("search/", views.Search.as_view(), name='search'),
    path("cart/",views. DisplayCart.as_view(), name='display_cart'),
    path("account-method/", views.ChooseAccountMethod.as_view() , name='choose_account_method'),
    path("create-order/", views.CreateOrder.as_view() , name='create_order'),
    path("order-confirmation/", views.OrderConfirmation.as_view() , name='order_confirmation'),
    path("categories/<int:pk>/", views.CategoriesIndex.as_view() , name='categories'),
    path("success/", views.DidSucces.as_view() , name='success'),
    path("dot_pay_return_values/", views.DidSucces.as_view() , name='dot_pay_return_values'),
    path("tags", views.TagsIndex.as_view() , name='tags'),
    path("add_to_cart/", views.add_to_cart , name='add_to_cart'),

]

Store/forms.py
from django import forms

from .models import Order

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = (
            'email', 'first_name', 'last_name',
            'house_number', 'street', 'city',
            'zip_code', 'voivodeship', 'additional_info'
            )



class DotPayForm(forms.Form):
    api_version = forms.CharField(widget = forms.HiddenInput())
    id = forms.IntegerField(widget = forms.HiddenInput())
    amount = forms.CharField(widget = forms.HiddenInput())
    currency = forms.CharField(widget = forms.HiddenInput())
    description = forms.CharField(widget = forms.HiddenInput())
    type = forms.IntegerField(widget = forms.HiddenInput())
    URL = forms.CharField(widget = forms.HiddenInput())
    URLC = forms.CharField(widget = forms.HiddenInput())
    bylaw = forms.CharField(widget = forms.HiddenInput())
    personal_data = forms.CharField(widget = forms.HiddenInput())

    firstname = forms.CharField(widget = forms.HiddenInput())
    lastname = forms.CharField(widget = forms.HiddenInput())
    email = forms.EmailField(widget = forms.HiddenInput())


Store/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, reverse
from django.http.response import JsonResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib import messages

from functools import reduce
from decimal import Decimal
import json
import urllib


from .models import Book, Author, Reader, Category, Tag, Order
from .cart import CART, Cart
from .forms import OrderForm, DotPayForm
from .tasks import send_confirmation_order_mail
from . import config


class Index(View):
    
    def get(self, request):
        
        books = Book.objects.all().order_by('title')
        paginator = Paginator(books, 12)
        page = request.GET.get('page')
        books_page = paginator.get_page(page)

        categories = Category.objects.all()

        return render(request, 'Store/index.html', 
                {
                'books': books_page, 
                'categories':categories,
                
                })


class BookDetail(View):
    def get(self, request, pk, slug):
        book = get_object_or_404(Book, pk=pk)
        other_books = [other_book for other_book in book.authors.all()[0].books.all() if other_book.pk != book.pk ] 
        
        observed_str = ""
        if request.user.is_authenticated:
            observed = request.user.observed.filter(pk=book.pk)
            if len(observed) != 0:
                observed_str= "observed"

        return render(request, 'Store/book_detail.html', {'book':book, 'other_books':other_books, 'observed':observed_str})



class AuthorIndex(View):

    def get(self, request):
        authors = Author.objects.all()

        return render(request, 'Store/author_index.html', {'authors':authors})


class AuthorDetail(View):

    def get(self, request, pk):

        author = get_object_or_404(Author, pk=pk)
        books = author.books.all()
        return render(request, 'Store/author_detail.html', {'author': author, 'books':books})


class Search(View):
    # TODO: integrate search with search engine
    def get(self, request):
        
        
        search = request.GET.get("search")
        
        if not search:
            return redirect(reverse("Store:index"))

        books = Book.objects.filter(title__contains=search)
        paginator = Paginator(books, 12)
        page = request.GET.get('page')
        books_page = paginator.get_page(page)
        
        categories = Category.objects.all()

        return render(request, 'Store/index.html', 
                {
                'books': books_page, 
                'categories':categories,
                
                })


class DisplayCart(View):

    def get(self, request):
        cart = Cart(request.session)
        cart.clean_cart()
        return render(request, 'Store/display_cart.html', {'cart':cart})


    def post(self, request):
        cart = Cart(request.session)
        cart.clean_cart()
        return redirect('Store:choose_account_method')



@csrf_exempt
def add_to_cart(request):
    
    data = json.loads(request.body)
    try:
        book_id, book_type, price, quantity = unpack_data(data)
        cart = Cart(request.session)
        try:
            cart.add_item(book_id, book_type, price, quantity)
        except ValueError:
            return JsonResponse({"status": "error", "error_msg":"quantity of item can not be less than 0"})
        
        return JsonResponse({"status": "ok"})

    except (ValueError, TypeError):
        return JsonResponse({"status":"error", "error_msg":"invalid data type"})
    except Book.DoesNotExist:
        return JsonResponse({"status":"error", "error_msg":"object does not exist"})
    except AttributeError:
        return JsonResponse({"status":"error", "error_msg":"invalid book type"})
    
    return JsonResponse({"status":"error", "error_msg": "unknown error"})


def unpack_data(data):
    
    book_id = int(data['id'])
    book = Book.objects.get(pk=book_id)
    book_type = data['type']
    price = getattr(book, book_type).price
    quantity = data['quantity']
    return book_id, book_type, price, quantity


class CategoriesIndex(View):

    def get(self, request, pk):
        # category = Category.objects.filter(slug=category_slug)
        category = get_object_or_404(Category, pk=pk)
        books = category.books.all()
        paginator = Paginator(books, 12)
        page = request.GET.get('page')
        books_page = paginator.get_page(page)

        categories = Category.objects.all()

        return render(request, 'Store/category_index.html', {'category':category, 'books':books_page, 'categories':categories})


class TagsIndex(View):

    def get(self, request):
        tags = request.GET.getlist('tag')
        tags = Tag.objects.filter(text__in=tags)
        books_page = []
        if(tags):
            books = Book.objects.filter(tags__in=tags)
            paginator = Paginator(books, 12)
            page = request.GET.get('page')
            books_page = paginator.get_page(page)
        return render(request, 'Store/tags.html', {"books":books_page})


class CreateOrder(View):

    def get(self, request):
        if request.user.is_authenticated:
            order_form = OrderForm(instance=request.user)
        else:
            order_form = OrderForm()
        return render(request, 'Store/create_order.html', {'order_form':order_form})
    
    def post(self, request):
        
        order_form = OrderForm(request.POST)
            
        if order_form.is_valid():
            order = order_form.save(commit=False)
            if request.user.is_authenticated:
                order.user = request.user
            order.save()
            cart = Cart(request.session)
            cart.clean_cart()
            items = cart.create_order_items(order)
            order.items.set(items)
            order.save() #TODO: Is it necessary, check
            request.session['order'] = order.pk
            del request.session[CART]
            return redirect(reverse('Store:order_confirmation'))
        
        return render(request, 'Store/create_order.html', {'order_form':order_form})


class OrderConfirmation(View):
    
    def get(self, request):
        order_id = request.session.get('order')
        order = Order.objects.get(pk=order_id)
        amount = reduce(lambda value, item:  value+ (Decimal(item.price)*item.quantity), order.items.all(), 0)
        currency = "PLN"
        url = urllib.parse.urljoin("http://127.0.0.1:8000", reverse('Store:success'))
        urlc = urllib.parse.urljoin("http://127.0.0.1:8000", reverse('Store:dot_pay_return_values'))
        firstname = order.first_name
        lastname = order.last_name
        email = order.email
        data_for_dot_pay = {
            'api_version':config.DOTPAY_API_VERSION,
            'id':config.DOTPAY_ID,
            'amount': amount,
            'currency': currency,
            'description' : f"Zamówienie dla {firstname} {lastname} na kwote {amount}",
            'firstname':firstname,
            'lastname':lastname,
            'email':email,
            'type': 4,
            'URL': url,
            'URLC': urlc,
            'bylaw':1 ,
            'personal_data': 1,
        }
        dotpay_form = DotPayForm(initial=data_for_dot_pay)
        order_pk = request.session.get('order')
        order = get_object_or_404(Order, pk=order_pk)
        items = order.items.all()
        if(order):
            return render(
                request,
                 'Store/order_confirmation_and_payment_method.html',
                  {
                      "order":order,
                      "items":items, 
                      "dotpay_form":dotpay_form,
                      "url":"https://ssl.dotpay.pl/test_payment/"
                  })
        

  
class DidSucces(View):

    def get(self, request):
        status_choices = ("new", "completed", "rejected")
        did_succes = request.GET.get("status")
        messages.success(request, 'Dziękujemy za zakupy!')

        return redirect(reverse("Store:index"))


def dotpay_server_confirmation(request):
    #TODO dokończyć potwierdzenie
    request.GET.get('id')
    request.GET.get('operation_number')
    request.GET.get('operation_type')
    request.GET.get('operation_status')
    request.GET.get('operation_amount')
    request.GET.get('operation_currency')
    request.GET.get('is_completed')
    request.GET.get('operation_original_amount')
    request.GET.get('operation_original_currency')
    request.GET.get('operation_datetime')
    request.GET.get('operation_related_number')
    request.GET.get('control')
    request.GET.get('description')
    email = request.GET.get('email')
    request.GET.get('control')

     
    subject = "Zlecenie potwierdzone"
    body = "Twoje zlecenie zostało potwierdzone. Dziękujemy za zakupy!"

    send_confirmation_order_mail.delay(email, subject, body)



    return HttpResponse("OK")



class ChooseAccountMethod(View):


    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse("Store:create_order"))
        form = AuthenticationForm()
        next = reverse('Store:order_confirmation')
        return render(request, 'Store/choose_account_method.html', {'form':form, 'next':next})

    def post(self, request):
        pass



Store/templates/Store/author_detail.html
{% extends "Store/base.html" %}

{% block css %}
{% load static%}

<link rel="stylesheet" type="text/css" href="{% static 'Store/css/author_detail.css' %}"> 
<link rel="stylesheet" type="text/css" href="{% static 'Store/css/book_detail.css' %}"> 
{% endblock css%}


{% block body %}
    <div class="author-container">
        <img class="author-image" src="{{author.avatar.url}}"/>
        <p class="author-name">{{ author }} </p>
    
        <div class="author-descr">
             {{ author.description }}
        </div>
    </div>

    <p id="other-books-header">Książki tego autora:</p>
    <div class="other-books-segment">
        {% if books.count > 5    %}
        <i class="material-icons arrows right">arrow_forward_ios</i>
        <div class="other-books centered" data-gap="{{books.count}}">    
            {% for book in books %}
                
                <a class="other-book" href="{% url 'Store:book_detail' book.id book.slug %}">
                    <img class="other-cover" src="{{book.cover_photo.url }}"/>
                    <p> {{book.title}} </p>
                    <p> {{book.first_available_type.price }}PLN</p>
                </a>
                {% endfor %}
        </div>
        <i class="material-icons arrows left">arrow_back_ios</i>
        {% else %}
        <div class="other-books" >    
                {% for book in books %}
                    
                    <a class="other-book " href="{% url 'Store:book_detail' book.id book.slug %}">
                        <img class="other-cover" src="{{book.cover_photo.url }}"/>
                        <p> {{book.title}} </p>
                        <p> {{book.first_available_type.price }}PLN</p>
                    </a>
                    {% endfor %}
        </div>
        {% endif %}
    </div>

{% endblock body %}

{% block javascript %}
{% if books.count > 5 %}
    <script type="text/javascript" src="{% static 'Store/js/gallery.js' %}" > </script> 
{% endif %}
{% endblock %}

Store/templates/Store/author_index.html
{% extends "Store/base.html" %}


{% block body %}
    {% for author in authors%}
        <a href="{% url 'Store:author_detail' author.pk %}">{{ author.first_name}} {{author.second_name}} {{author.last_name}} </a>

    {% endfor %}
{% endblock body %}

Store/templates/Store/book_detail.html
{% extends "Store/base.html" %}

{% block css %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'Store/css/book_detail.css' %}"> 
{% endblock css%}


{% block body %}
    <div class="layout">
        <div class="book-container">
            <img class="book-cover" src="{{book.cover_photo.url }}"/>
            
            <div class="book-info">
                <h1 class="title">{{book.title }}<i id="add-to-favourites" class="material-icons {{ observed }}" data-book-id="{{book.id}}" onclick="addToObserved(event)">star_border </i> 
                </h1>
                
                <span class="pre">Autor:</span>
                {% for author in book.authors.all %}
                    <a href="{% url 'Store:author_detail' author.id %} " class="author">{{ author }}</a>
                {% endfor %}
                
                <a href="{% url 'Store:categories' book.category.id %}" class="category">{{book.category}}</a>
            </div>
            <div class="shop-info">
                <div class="segment-title">Dostępne formaty:</div>
                {% if book.ebook %}
                <div class="ebook choosable"  onclick="chooseType(event);">
                    <div data-book-id="{{book.id}}" 
                        data-book-type="ebook"
                        data-book-price="{{book.ebook.price}}">
                        <p class="book-type">
                            ebook
                        </p>
                        <p class="price">
                            {{ book.ebook.price}}   PLN
                        </p>
                    </div>
                </div>
                {% endif %}
                {% if book.audio_book%}
                <div class="audio-book choosable"  onclick="chooseType(event);">
                    <div data-book-id="{{book.id}}" 
                        data-book-type="audio_book"
                        data-book-price="{{book.audio_book.price}}">
                        <p class="book-type">
                            audiobook
                        </p>
                        <p class="price">
                            {{ book.audio_book.price}} PLN
                        </p> 
                    </div>   
                </div>
                {% endif %}
                {% if book.paper_book %}
                <div class="paper-book choosable" onclick="chooseType(event);" >
                    <div data-book-id="{{book.id}}" 
                        data-book-type="paper_book"
                        data-book-price="{{book.paper_book.price}}">
                        <p class="book-type">
                            {{book.paper_book.cover }}
                        </p>
                        <p class="price">
                            {{book.paper_book.price }} PLN
                        </p>
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="tags">
                <div class="segment-title">Tagi:</div>
                    {% for tag in book.tags.all %}
                        <a class="tag" href="{% url 'Store:tags' %}?tag={{tag.text}}">#{{tag}}</a>
                    {% endfor %}
            </div>
            
            
            <div class="book-description">
                <div class="segment-title">Opis: </div>
                {{book.description}}
            </div>
    
        </div>

        <div class="price-info">
                <div class="">
                    
                    <div id="swapable">
    
                            <div>
                                {% with book_type=book.first_available_type %}
                                <div class="book-type">
                                    <span class="pre">Format: </span>{{book_type}}
                                </div>
                            
                                <p class="price"><span class="pre">Cena: </span>{{book_type.price}} PLN</p>
                                {% endwith %}
                            </div>
                    </div>
                    <span class="pre">Ilość:</span>
                    <i id="remove-icon" class="small material-icons" onclick="changeQuantityValue(-1)">remove</i>
                    <input id="quantity" type="text" value="1" /> 
                    <i id="add-icon" class="small material-icons" onclick="changeQuantityValue(1)">add</i>
                    <a id="add-to-cart"
                        href="#"
                        onclick="addToCartFromInput(event)"
                        data-book-id="{{book.id}}" 
                        data-book-type="paper_book"
                        data-book-price="{{book.paper_book.price}}">
                        <i id="add-cart-icon" class="material-icons">add_shopping_cart</i>Dodaj do wózka
                    </a>
                </div>
                
            </div>
    </div>
    
    <div id="other-books-segment">
        <p id="other-books-header">Inne książki tego autora:</p>
        
        {% for other_book in other_books %}

            <a class="other-book" href="{% url 'Store:book_detail' other_book.id other_book.slug %}" >
                <img class="other-cover" src="{{ other_book.cover_photo.url }}"/>
                <p> {{other_book}}</p>
                <p> {{other_book.paper_book.price}} PLN </p>   
            </a>
        
        {% endfor %}
    </div>

{% endblock body %}


{% block javascript %}

<script type="text/javascript" src="{% static 'Store/js/quantityForm.js' %}" > </script> 
<script type="text/javascript" src="{% static 'Store/js/addToCart.js' %}" > </script> 
<script type="text/javascript" src="{% static 'js/getCookie.js' %}" > </script> 
<script type="text/javascript" src="{% static 'Store/js/addToObserved.js' %}" > </script> 

{% endblock javascript %}

Store/templates/Store/books_index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Store/css/display_book.css' %}"> 


{% if messages %}



{% for message in messages %}
    <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
{% endif %}
<div class="book-preview-containter">
    {% for book in books %}
 
            
            <div class="book-preview">
                {% load static %}
                <a class="cover-image-link" href="{% url 'Store:book_detail' book.id book.slug %}">
                    <img class="cover-image" src="{{ book.cover_photo.url }}" alt="{{ book.title }}"/>
                </a>

                {% with book_type=book.first_available_type %}

                <a class="addToCart-button" href="#" onclick="addToCart(event);"
                    data-book-id="{{book.id}}" 
                    data-book-type="{{book_type}}"
                    data-book-price="{{book_type.price}}">
                    <i id="add-cart-icon" class="material-icons">add_shopping_cart</i>Dodaj do wózka
                </a>


                <a class="title" href="{% url 'Store:book_detail' book.id book.slug %}">{{ book.title }}</a>
                {% for author in book.authors.all %}
        
                    <a class="author" href="{% url 'Store:author_detail' author.pk  %}" >{{ author }}</a>
                {% endfor %}
                
                <div>
                    
                    <p class="book-type">{{ book_type }}</p>
                    <p class="price">{{ book_type.price }} PLN</p>
                </div>

                {% endwith %}
            </div>
            
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if books.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ books.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ books.number }} of {{ books.paginator.num_pages }}.
                </span>
        
                {% if books.has_next %}
                    <a href="?page={{ books.next_page_number }}">next</a>
                    <a href="?page={{ books.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

Store/templates/Store/category_index.html
{% extends "Store/base.html" %}

{% block css %}
{% load static%}
    <link rel="stylesheet" type="text/css" href="{% static 'Store/css/display_book.css' %}"> 
    <link rel="stylesheet" type="text/css" href="{% static 'Store/css/index.css' %}"> 
{% endblock css%}


{% block body %}
<div class="index-main-container">
        <div class="categories">
            <div class="categories-title">Kategorie:</div>
            {% for iter_category in categories %}
                {% if category == iter_category %}
                
                <a class="category-link activated" href="{% url 'Store:categories' iter_category.id %}">{{ iter_category|capfirst}}</a>
                {% else %}
                <a class="category-link " href="{% url 'Store:categories' iter_category.id %}">{{ iter_category|capfirst}}</a>
                {% endif %}
            {% endfor %}
        </div>
        
        {% include "Store/books_index.html" %}
    
       
    </div>

{% endblock body %}


{% block javascript %}
<script type="text/javascript" src="{% static 'Store/js/addToCart.js' %}" > </script> 
<script type="text/javascript" src="{% static 'js/getCookie.js' %}" > </script> 
{% endblock javascript %}

Store/templates/Store/choose_account_method.html
{% extends "Store/base.html" %}

{% block css %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'Store/css/login_form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'Store/css/choose_account_method.css' %}">
{% endblock css%}

{% block body %}
    
        <div class="container">
            <div class="method">
                <form class="login-form" method="post" action="{% url 'login' %}">
                    <p class="header-like">Logowanie</p>
                    {% csrf_token %}
                  
                    <div class="input-field">
                      
                        {{ form.username.label_tag }}
                        {{ form.username }}
                        
                    </div>
                    <div>
                      
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    
                    </div>
            
                    <input type="submit" value="Zaloguj" />
                    <input type="hidden"  name="next" value="{{ next }}" />
                    
                    
                    <p id="lost-password" class="smaller-faded"><a href="{% url 'password_reset' %}">Lost password?</a></p>
                </form>
                
                <div class="register">
                    <p class="header-like">Rejestracja</p>
                    <p class="smaller-faded ">Nie masz konta? Zarejestruj się!</p>
                    <a class="register-button" href="{% url 'Account:sign_up' %}">Rejestracja</a>  
                </div>  
            </div>
        
            <div class="spaceing">
                <p class="header-like">Kup bez rejestracji</p>
                <p class="smaller-faded" >Nie masz konta i nie chcesz go zkładać?</p>
                <a class="without-account-button" href="{% url 'Store:create_order' %}">Zapłać bez konta</a>
            
            </div>
        </div>



{% endblock body %}

Store/templates/Store/display_cart.html
{% extends 'Store/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Store/css/display_cart.css' %}">
{% endblock css %}


{% block body %}

{% if cart %}



        
        <div class="cart-container">
            
            <div class="items">
                <div class="pre-cart">Mój koszyk:</div>
                <div class="cart-item-preview label">
                        <span></span>
                        <div class="book-info">Książka:</div>
                        <span class="quantity">Ilość:</span>
                        <span class="price">Cena pojedyncza:</span>
                        <span class="total-price">Cena łączna:</span>    
                </div>
                {% for item in cart %}
                    <div class="cart-item-preview">
                        <img class="cover-image-cart" src="{{ item.book.cover_photo.url }}"></i>
                        <div class="book-info">
                            <p class="title"><span class="pre-type">Tytuł:</span>{{ item.book.title }}</p>
                            <p class="author"><span class="pre-type">Autor:</span> {% for author in item.book.authors.all %}
                                {{ author}}
                                {% endfor %}
                            </p>
                            <p class="book-format"><span class="pre-type">Format:</span>{{ item.book_type }}</p>
                        </div>
                        <div
                            class="data-element quantity-change"
                            data-book-id="{{item.book.id}}" 
                            data-book-type="{{item.book_type}}"
                            data-book-price="{{item.book_type.price}}">
                           
                            <i id="remove-icon" class="small material-icons">remove</i>
                            <span class="quantity-value">{{ item.quantity }}</span>
                            
                            <i id="add-icon" class="small material-icons" >add</i>
                        </div>
                        <span class="price"><span class="pre-type">Cena pojedyncza:</span>{{ item.book_type.price }}PLN</span>
                        {% load multiply_tag %}
                        <div class="total-price"><span class="pre-type">Cena łączna:</span><span class="total-price-text">{% multiply item.book_type.float_price item.quantity %}PLN</span></div>

                        
                       
                    </div>
                 {% endfor %}
            </div>
             
             
             <div class="cart-summary">
                <p><span class="less-important">Całkowity koszt:</span>
                    <span class="total-price-text">{{global_cart.price}}PLN</span></p>
                <p >
                    <span class="less-important">Ilość przedmiotów:</span> 
                    <span class="quantity-second">{{global_cart.quantity}}</span>
                </p>
    
                <form action="{% url 'Store:display_cart' %}" method="post">
                    {% csrf_token %}
                    {% if global_cart.quantity == 0 %}
                    <button id="go-to-payment" type="submit" disabled>Zapłać</button>
                    {% else %}
                    <button id="go-to-payment" type="submit">Zapłać</button>
                    {% endif %}
                </form>
             </div>
        </div>
    

{% else %}
 <p>Nic tu nie ma</p>
{% endif %}

{% endblock body %}


{% block javascript %}
<script type="text/javascript" src="{% static 'Store/js/addToCart.js' %}" > </script> 
<script type="text/javascript" src="{% static 'Store/js/displayCart.js' %}" > </script> 
{% endblock %}