Account/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import  SignUp, AccountOptions, OrderHistory, ObservedBooks

app_name = 'Account'

urlpatterns = [
       path("", AccountOptions.as_view(), name="account_options" ),
       path("order-history/", OrderHistory.as_view(), name="order_history" ),
       path("signup/", SignUp.as_view(), name="sign_up" ),
       path("observed-books/", ObservedBooks.as_view(), name="observed_books" ),
       path("observed-books/<int:pk>/", ObservedBooks.as_view(), name="observed_books" ),
]

BookStore/urls.py

from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('Store.urls', namespace='Store')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Account.urls', namespace='Account')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name =  'Store'

urlpatterns = [
    path("", views.Index.as_view(), name='index'),
    path("books/<int:pk>/<slug:slug>/", views.BookDetail.as_view(), name='book_detail'),
    path("authors/", views.AuthorIndex.as_view(), name='author_index'),
    path("authors/<int:pk>/", views.AuthorDetail.as_view(), name='author_detail'),
    path("search/", views.Search.as_view(), name='search'),
    path("cart/",views. DisplayCart.as_view(), name='display_cart'),
    path("account-method/", views.ChooseAccountMethod.as_view() , name='choose_account_method'),
    path("create-order/", views.CreateOrder.as_view() , name='create_order'),
    path("order-confirmation/", views.OrderConfirmation.as_view() , name='order_confirmation'),
    path("categories/<int:pk>/", views.CategoriesIndex.as_view() , name='categories'),
    path("success/", views.DidSucces.as_view() , name='success'),
    path("dot_pay_return_values/", views.DidSucces.as_view() , name='dot_pay_return_values'),
    path("tags", views.TagsIndex.as_view() , name='tags'),
    path("add_to_cart/", views.add_to_cart , name='add_to_cart'),

]

templates/global_footer.html
<footer>
    <div>Strona została stworzona przez Mateusza Klaczyńskiego w ramach ćwiczeń. Nie można na niej nic kupić!</div>
    <div>Link do <a href="https://github.com/OnufryKlaczynski">githuba</a></div>
    <div>Zapraszam do współpracy mateusz.klaczynski@gmail.com</div>
</footer>

templates/global_header.html

<header>
    <i id="menu" class="material-icons">menu</i>
                
    <h1 id="logo"><a href="{% url 'Store:index' %}">MojeLogo</a></h1>
    <form id="search" name="search" method="get" action="{% url 'Store:search' %}">
        <input id="search-input" 
            type="text" 
            placeholder="Czego szukasz?"
            name="search"
            onfocus="changeSearchFormColorOnFocus();" 
            onblur="changeSearchFormColorOnBlur();"
        >
        <button action="{% url 'Store:search' %}" type="submit">
            <i class="material-icons">search</i>
        </button>
    </form>
    {% if user.is_authenticated %}

    <a id="favourites"  href="{% url 'Account:observed_books' %}"><span class="pre-header">Obserwowane</span><i class="material-icons">star_border</i></a>
    <a id="settings" href="{% url 'Account:account_options' %}"><span class="pre-header">Konto</span><i class="material-icons">account_circle</i></a>
    {% else %}
        <a id="favourites" href="{% url 'Account:sign_up' %}">Zarejestruj się</a>
        <a id="settings" href="{% url 'login' %}">Zaloguj się</a>

    {% endif %}
    <a href="{% url 'Store:display_cart' %}">
        <div id="cart">
            {% if global_cart %}
                
                <span>
                    <i class="material-icons">shopping_cart</i>
                    <span id="cart-quantity-wrapper"><span id="cart-quantity"> {{ global_cart.quantity }}</span></span>
                </span>
                
                <span id="cart-price"> {{ global_cart.price }}PLN </span>
            {% else %}
                <span> Brak przedmiotów </span>
            {% endif %}
        <div>
    </a>

</header>
{% load static %}
<script type="text/javascript" src="{% static 'js/dropdownMenu.js' %}" > </script> 